from .merlict_c89_wrapper.wrapper import Quaternion
from .merlict_c89_wrapper.wrapper import Quaternion_set_unit_xyz as set_unit_xyz
from .merlict_c89_wrapper.wrapper import Quaternion_set_tait_bryan as set_tait_bryan
from .merlict_c89_wrapper.wrapper import Quaternion_set_rotaxis_and_angle as set_rotaxis_and_angle